<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer: 
The input layer are the features for the models. They take in the raw data and send it to the network. They may also be referred to as the visible layer. 

In the example given at the beginning of lecture, the inputs for predicting the sale price of a home would be things like square footage, number of bedrooms, bathrooms, etc. 

### Hidden Layer:
Hidden layers are used in neural network and can be picked based on experience, experimentation or arbitrarily. We don't really see their values. 

### Output Layer:
The output layer is what is being predicted. In binary classification or a simple regression (like the sale price of a house) there will be 1 node. In a multi-class or multi-target regression problem there will be as many nodes as possible outputs.

### Neuron:
A neuron takes each of the input values given and multiplies them by a weight, sums these products and passes the sum through an activation function which calculates the output. Basically they receive inputs and pass on their signal to the next layer of the neural network.

### Weight:
Each input node has a weight that can be derrived from the data itself (average price per square foot) or can be automated along with the bias term through gradient descent. 

### Activation Function:
An activation function can be referred to as a transfer function. Each node in a neural network has one and they are usually the same within each layer of the network. They decide how much signal to pass onto the next layer. Sigmoid and tanh are the most commonly used activation functions. 

### Node Map:
A node map is the visual representation of the achitecture of a neural network. Most consist of some variation of a input layer, hidden layer, and output layer. There are other possibilities for cells and vary widely on complexity.

### Perceptron:
A perceptron is a simple neural network. It's a single node or neuron of a neural network. It can have any number of inputs and will produce an output.

## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

Using the home price example:

Say there are 3 inputs when determining price -- sq ft, number of bathrooms, number of bedrooms:

input1 = 2000sq ft, weight1 = 180 (average price per sq ft of data) 
input2 = 4 bathrooms, weight2 = 200 (average price per bathroom of data)
input3 = 6 bedrooms, weight3 = 350 (average price per bedroom of data)
activation function = sigmoid
bias = 175 (picked arbitrarily)

output = sigmoid((weight1 * input1) + (weight2 * input2) + (weight3 * input3) + bias)
![flownn](https://schwalbe10.github.io/thinkage/images/posts/perceptron.png)

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [10]:
import pandas as pd
import numpy as np
data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')

In [2]:
df.head()

x1  x2  y
0   0   0  1
1   1   0  1
2   0   1  1
3   1   1  0

In [54]:
inputs = np.array(df[['x1', 'x2']])
outputs = np.array(df[['y']])
print(inputs)
outputs

[[0 0]
 [1 0]
 [0 1]
 [1 1]]


array([[1],
       [1],
       [1],
       [0]])

In [55]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# need this because will update weights based on
# probabilities:
def sigmoid_derivative(x):
    sx = sigmoid(x)
    return sx * (1-sx)

In [91]:
# randomize bias:
bias = 2 * np.random.random((1,1)) - 1
bias

array([[-0.4455051]])

In [92]:
# randomize weights for inputs:
weights = 2 * np.random.random((2,1)) - 1
weights

array([[-0.67927179],
       [ 0.9724784 ]])

In [93]:
# weighted sums of inputs and weights
weighted_sum = np.dot(inputs, weights) + bias
weighted_sum

array([[-0.4455051 ],
       [-1.12477689],
       [ 0.5269733 ],
       [-0.15229849]])

In [94]:
# predictions:
activated_output = sigmoid(weighted_sum)
activated_output

array([[0.39043   ],
       [0.24512629],
       [0.62877691],
       [0.4619988 ]])

In [95]:
# calculate error:
error = outputs - activated_output
error

array([[ 0.60957   ],
       [ 0.75487371],
       [ 0.37122309],
       [-0.4619988 ]])

In [96]:
# gradient descent:
adjusted = error * sigmoid_derivative(activated_output)
adjusted

array([[ 0.14672941],
       [ 0.1859117 ],
       [ 0.08420509],
       [-0.10954935]])

In [97]:
# new size of weights:
weights += np.dot(inputs.T, adjusted)
weights

array([[-0.60290944],
       [ 0.94713413]])

In [99]:
# Update our weights 10,000 times - (fingers crossed that this process reduces error)
for iteration in range(10000):
    
    # Weighted sum of inputs / weights
    weighted_sum = np.dot(inputs, weights) + bias
    
    # Activate!
    activated_output = sigmoid(weighted_sum)
    
    # Cac error
    error = outputs - activated_output
    
    adjustments = error * sigmoid_derivative(activated_output)
    
    # Update the bias
    bias += np.mean(error)
    
    # Update the Weights
    weights += np.dot(inputs.T, adjustments)
    
print("Weights after training")
print(weights)

print("Output after training")
print(activated_output)

Weights after training
[[-12.55141605]
 [-12.55141605]]
Output after training
[[0.99999999]
 [0.99833495]
 [0.99833495]
 [0.00211839]]


## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [165]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [167]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

feats = list(diabetes)[:-1]

X = np.array(diabetes[feats])
y = np.array(diabetes[['Outcome']])

MinMax = MinMaxScaler()
X = MinMax.fit_transform(X)

In [202]:
class Perceptron(object):
    
    def __init__(self, niter = 10):
        self.niter = niter
    
    def __sigmoid(x):
        return 1 / (1 + np.exp(-x))
    
    def __sigmoid_derivative(x):
        sx = Perceptron.__sigmoid(x)
        return sx * (1-sx)

    def fit(self, X, y):
        """Fit training data
        X : Training vectors, X.shape : [#samples, #features]
        y : Target values, y.shape : [#samples]
        """

        # Randomly Initialize Weights
        self.weights = 2 * np.random.random((X.shape[1], 1)) -1
    
        # Randomly Initialize Bias
        self.bias = 2 * np.random.random() - 1

        for i in range(self.niter):
        
            # Weighted sum of inputs / weights
            weighted_sum = np.dot(X, self.weights) + self.bias
        
            # Activate!
            activated_output = Perceptron.__sigmoid(weighted_sum)
        
            # Calc error
            error = y - activated_output
            
            # Update the Weights & Bias
            adjustments = error * Perceptron.__sigmoid_derivative(activated_output)
            self.weights += np.dot(X.T, adjustments)
            self.bias += np.mean(error)

    def predict(self, X):
        """Return class label after unit step"""
        
        weighted_sum = np.dot(X, self.weights) + self.bias
        return np.round(Perceptron.__sigmoid(weighted_sum))


In [203]:
# instantiate
model = Perceptron(niter = 10000)

In [204]:
# fit model
model.fit(X, y)

In [205]:
test = model.predict(X)
test = test.astype(int)
test[:10]

array([[1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0]])

In [201]:
# actual
y[:10]

array([[1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1]])

In [206]:
# not sure how to score this...
from sklearn.metrics import accuracy_score

accuracy_score(test, y)

0.7395833333333334

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?